---
- hosts: all
  vars_files:
  - "secrets"
  become: yes
  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Helper packages
    ansible.builtin.apt:
      pkg:
        - vim
        - htop
        - tmux
        - xxd

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Reboot machine
    ansible.builtin.reboot:
      msg: "Patch complete - rebooting"