---
- hosts: all
  vars_files:
  - "secrets"
  become: yes
  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Helper packages
    ansible.builtin.apt:
      pkg:
        - vim
        - htop
        - tmux
        - xxd
        - sqlite3

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Reboot machine
    ansible.builtin.reboot:
      msg: "Patch complete - rebooting"
      reboot_timeout: 600
      pre_reboot_delay: 60
      post_reboot_delay: 30
      connect_timeout: 5
      test_command: uptime

  - name: Mount # run mount -a since gluster is not fully up by the time fstab is mounted on boot
    ansible.builtin.shell: mount -a