- hosts: proxy
  vars_files:
  - "secrets"
  become: yes
  tasks:
    - name: 'Caddy signing key'
      ansible.builtin.shell: curl -fsSL 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /etc/apt/keyrings/caddy-stable-archive-keyring.gpg

    - name: 'Caddy repo'
      apt_repository:
        repo: deb [signed-by=/etc/apt/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present

    - name: 'Caddy install'
      apt:
        pkg:
          - caddy
          - ufw
        state: present

    - name: 'Start caddy'
      ansible.builtin.service:
        name: caddy
        enabled: yes
        state: started

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow ssh mimited ssh
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - community.general.ufw:
        rule: allow
        port: http

    - community.general.ufw:
        rule: allow
        port: https