- hosts: proxy
  vars_files:
  - "secrets"
  become: yes
  tasks:
    - name: 'Nginx install'
      apt:
        pkg:
          - nginx
          - ufw
        state: present

    - name: 'Start nginx'
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow ssh mimited ssh
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - community.general.ufw:
        rule: allow
        port: http

    - community.general.ufw:
        rule: allow
        port: https